export const categories = [
  "Beauty",
  "Cleaning",
  "Repair",
  "Home Services",
  "Education",
  "Fitness",
  "Photography",
  "Pet Care",
  "Delivery",
  "Moving",
  "Events",
  "Car Services",
  "Programming",
  "Design",
  "Other",
];